version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odoo_network

  odoo:
    image: odoo:17.0
    depends_on:
      - postgres
    ports:
      - "8070:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons  # Mapea la carpeta local a /mnt/extra-addons en Odoo
    environment:
      - HOST=postgres
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo_network

volumes:
  postgres_data:
  odoo_data:

networks:
  odoo_network:
    driver: bridge
